### ISSUE TITLE
"fody weavingtask" failed not given a value for the parameter "solutiondir"

### ISSUE THREAD

**Issue by alesper3** [bp2008/IPScanner#1]
"fody weavingtask" failed not given a value for the parameter "solutiondir"

**Comment by bp2008** [comment]
I'm not sure if you are trying to build or just run it.  Either way I've never seen such an error.

If you are trying to build, you can just remove the fody and costura.fody packages from the nuget manager GUI thing and it should build just fine without them (it simply won't merge the referenced DLLs all into the main exe).
